### ISSUE TITLE
Body Type keeps changing to the male

### ISSUE THREAD

**Issue by Apple0293** [LiberatedPixelCup/Universal-LPC-Spritesheet-Character-Generator#65]
As the title says, every time I click on a different body type or change anything the body type changes to the male body type. I have to click the body type I choose every time I change anything. Is someone having the same issue or is it only on my end?

**Comment by jrconway3** [comment]
Apologies, we've been working on a lot of adjustments lately, but sometimes when making adjustments things break. I hadn't been fully testing the latest updates that went out because I've been busy, so I didn't notice that this bug occurred. Its definitely a bug, I can assure you; this issue was never happening before.

Yeah, its definitely acting wonky right now. Sanderfrenken already put out a PR, so I'll run some tests on it so we can get this issue resolved ASAP.



> But the clothes dont appear on half the animations or really anything for that matter? is this happening to you to??

This issue has already been addressed. I get that you want to see them, but it takes a long time to go through these assets. Most of these animations never had any assets on them before; originally this generator only included the animations up to "down". Last year we started adding the extra animations and I did a lot of work in adding assets.

Use the Animations filter to filter assets by supported animations and you'll see plenty of things that support these:
![supported-animation](https://github.com/user-attachments/assets/5dc0af69-a0a3-4e71-8bfa-571a58f349d5)


And if you want to see them completed, you're more than welcome to contribute:
https://github.com/LiberatedPixelCup/Universal-LPC-Spritesheet-Character-Generator/issues/38

But if you can't contribute, then you'll just have to be patient. Like I said in the other issue you created that I closed (as a duplicate), I want to get all of them completed. But its going to take a long time to get through everything. You'll just have to be patient. And please READ before posting.

Issue #38 is the issue we have set aside for filling out assets across the remaining frames. I will close any new issues created asking about this as a duplicate of that issue.

**Comment by sanderfrenken** [comment]
Fixed by https://github.com/LiberatedPixelCup/Universal-LPC-Spritesheet-Character-Generator/pull/64

**Comment by jrconway3** [comment]
I'm still having this issue appear. How long does it take for it to take effect? I assume its immediate and the file is just cached, but anyone who has the file cached is still going to have the problem. I've gotten used to updating a version number on files with my main job because it can be a PITA when users have a file cached and they have no idea how to clear the cache.

**Comment by jrconway3** [comment]
As far as I can tell its working now, but I still worry some users might have it cached.

Anywhere, there's another bug that was happening. Gaurav was trying to fix that bug, which is what caused this bug to happen.

**Comment by sanderfrenken** [comment]
> I'm still having this issue appear. How long does it take for it to take effect? I assume its immediate and the file is just cached, but anyone who has the file cached is still going to have the problem. I've gotten used to updating a version number on files with my main job because it can be a PITA when users have a file cached and they have no idea how to clear the cache.

Github pages needs to deploy the site. This usually takes a couple of minutes.
